[package]
name = "enum-spanner-rs"
version = "0.1.0"
authors = ["Rémi Dupré <remim.dupre@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
indicatif = "0.11"
rand = "0.6"
regex-syntax = "0.6"
