[package]
name = "enum-spanner-rs"
version = "0.1.0"
authors = ["Rémi Dupré <remim.dupre@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
regex = "1"
regex-syntax = "0.6"
bit-vec = "0.5.1"
bit-set = "0.5.1"
streaming-stats = "0.2.2"
serde_json = "1.0"
serde = { version = "1.0", features= ["derive"]}

[profile.dev]
opt-level = 3
